name: Maven CI/CD Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '24'
        cache: 'maven'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Test with Maven
      run: mvn -B test --file pom.xml
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: target/*.jar
        retention-days: 5